
source 'https://rubygems.org'
gem 'distribution'
gem 'fortune'
gem 'hashie'
gem 'jsonpath', '=0.8.6'
gem 'pg'
gem 'pg_query', '=0.13.2'
gem 'pry'
gem 'rspec'
gem 'rubytree'
gem 'trollop'
gem 'activesupport'
gem 'decisiontree'
# gem 'graphr'
